#!/usr/bin/env bash
# Creates a file containing its PID.
# Displays:
#	'To infinity and beyond' indefinitely.
#	'I hate the kill command' when receiving a SIGTERM signal.
#	'Y U no love me?!' when receiving a SIGINT signal.
# Deletes the file containing its PID and terminates itself
#+ when receiving a SIGQUIT or SIGTERM signal.

FILE="/var/run/myscript.pid"
pgrep -f "$0" > "$FILE"

trap 'rm -rf "$FILE" ; echo "I hate the kill command" ; exit' SIGTERM SIGQUIT
trap 'rm -rf "$FILE" ; echo "Y U no love me?!" ; exit' SIGINT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
