#!/usr/bin/env bash
# Displays:
#	'To infinity and beyond' indefinitely
#	'I am invincible!!!' when receiving a SIGTERM signal
# with a 'sleep 2' in between every iteration

trap "echo 'I am invincible!!!'" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
